export const supportedNetwork = [
    {
        name: "Mainnet",
        chainIdHex: "0x1",
        chainIdNumber: 1,
        explorer: "https://etherscan.io",
        logo: "/network/ethereum.svg",
        ticker: "ETH",
    },
    {
        name: "Base",
        chainIdHex: "0x2105",
        chainIdNumber: 8453,
        explorer: "https://basescan.org",
        logo: "/network/base.svg",
        ticker: "ETH",
    },
    {
        name: "BSC",
        chainIdHex: "0x38",
        chainIdNumber: 56,
        explorer: "https://bscscan.com",
        logo: "/network/bsc.svg",
        ticker: "BNB",
    },
    {
        name: "Sepolia",
        chainIdHex: "0xaa36a7",
        chainIdNumber: 11155111,
        explorer: "https://sepolia.etherscan.io",
        logo: "/network/ethereum.svg",
        ticker: "ETH",
    },
    {
        name: "Base Sepolia",
        chainIdHex: "0x14a34",
        chainIdNumber: 84532,
        explorer: "https://sepolia.basescan.org",
        logo: "/network/base.svg",
        ticker: "ETH",
    },
    {
        name: "BSC Tesnet",
        chainIdHex: "0x61",
        chainIdNumber: 97,
        explorer: "https://testnet.bscscan.com",
        logo: "/network/bsc.svg",
        ticker: "BNB",
    },
]