export const supportedNetwork = [
    {
        networkName: "Mainnet",
        chainIdHex: "0x1",
        chainIdNumber: 1,
        rpcUrl: "https://1rpc.io/eth",
        explorer: "https://etherscan.io",
        networkLogo: "/network/ethereum.svg",
        nativeCurrency: "ETH",
    },
    {
        networkName: "OP Mainnet",
        chainIdHex: "0xa",
        chainIdNumber: 10,
        rpcUrl: "https://mainnet.optimism.io",
        explorer: "https://optimistic.etherscan.io",
        networkLogo: "/network/op.svg",
        nativeCurrency: "ETH",
    },
    {
        networkName: "Base",
        chainIdHex: "0x2105",
        chainIdNumber: 8453,
        rpcUrl: "https://mainnet.base.org",
        explorer: "https://basescan.org",
        networkLogo: "/network/base.svg",
        nativeCurrency: "ETH",
    },
    {
        networkName: "BSC",
        chainIdHex: "0x38",
        chainIdNumber: 56,
        rpcUrl: "https://bsc-dataseed.bnbchain.org",
        explorer: "https://bscscan.com",
        networkLogo: "/network/bsc.svg",
        nativeCurrency: "BNB",
    },
    // Testnet Network
    {
        networkName: "Sepolia",
        chainIdHex: "0xaa36a7",
        chainIdNumber: 11155111,
        rpcUrl: "https://rpc.sepolia.org",
        explorer: "https://sepolia.etherscan.io",
        networkLogo: "/network/ethereum.svg",
        nativeCurrency: "ETH",
    },
    {
        networkName: "Base Sepolia",
        chainIdHex: "0x14a34",
        chainIdNumber: 84532,
        rpcUrl: "https://sepolia.base.org",
        explorer: "https://sepolia.basescan.org",
        networkLogo: "/network/base.svg",
        nativeCurrency: "ETH",
    },
    {
        networkName: "BSC Tesnet",
        chainIdHex: "0x61",
        chainIdNumber: 97,
        rpcUrl: "https://bsc-testnet-dataseed.bnbchain.org",
        explorer: "https://testnet.bscscan.com",
        networkLogo: "/network/bsc.svg",
        nativeCurrency: "BNB",
    },
]